### PR TITLE
Using classic array instead of array symbol

### LINKED ISSUE #41: Compile error on Chef 11
Hello, 

I'm having trouble running `chef-vault 1.3.2` on nodes running Chef 11. When trying to converge, the following error appears:

```
SyntaxError
-----------
/var/chef/cache/cookbooks/chef-vault/libraries/matchers.rb:2: unknown type of %string
  %i(create update delete create_if_missing).each do |action|
```

I suspect this is because doing `i%(foo bar)` is a Ruby 2.x feature and Chef 11 embeds Ruby 1.9.

### PR DESCRIPTION
**Pull request by RedWhiteMiko**
Fix #41

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## Non-GitHub Verified Committers

There are 1 commit author(s) whose commits are authored by a non-GitHub verified email address. Chef will have to manually verify that they are authorized to contribute.

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by luckymike** [comment]
@RedWhiteMiko any chance you can sign the Chef CLA so they will merge this?

**Comment by tas50** [comment]
I'm merging this under the obvious fix policy

**Comment by luckymike** [comment]
❤️ A policy you can love!

**Pull request merged**
